# Generated by Django 4.2.6 on 2024-01-16 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('author', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('english_text', models.TextField()),
                ('chinese_translation', models.TextField(blank=True, null=True)),
                ('token_count', models.IntegerField(blank=True, null=True)),
                ('has_clause', models.BooleanField(default=False)),
                ('has_non_finite_verb', models.BooleanField(default=False)),
                ('prep_count', models.IntegerField(blank=True, null=True)),
                ('conj_count', models.IntegerField(blank=True, null=True)),
                ('sub_count', models.IntegerField(blank=True, null=True)),
                ('obj_count', models.IntegerField(blank=True, null=True)),
                ('verb_count', models.IntegerField(blank=True, null=True)),
                ('noun_count', models.IntegerField(blank=True, null=True)),
                ('adj_count', models.IntegerField(blank=True, null=True)),
                ('adv_count', models.IntegerField(blank=True, null=True)),
                ('pron_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('english_text', models.TextField()),
                ('chinese_translation', models.TextField()),
                ('token_count', models.IntegerField(null=True)),
                ('sentence_count', models.IntegerField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passages.book')),
                ('sentences', models.ManyToManyField(to='passages.sentence')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(to='passages.category'),
        ),
    ]
