# Generated by Django 4.2.6 on 2024-01-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='chinese_translation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='sentence_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='sentences',
            field=models.ManyToManyField(blank=True, to='passages.sentence'),
        ),
        migrations.AlterField(
            model_name='passage',
            name='token_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
