# Generated by Django 4.2.6 on 2024-01-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0002_alter_passage_chinese_translation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='categories',
            field=models.ManyToManyField(blank=True, to='passages.category'),
        ),
    ]
