# Generated by Django 4.2.6 on 2024-01-16 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0003_passage_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passage',
            name='categories',
        ),
    ]
