# Generated by Django 4.2.6 on 2024-01-16 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0005_alter_passage_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='passages.book'),
        ),
    ]
