# Generated by Django 4.2.6 on 2024-01-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0007_token_passage_gpt_response_academic_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='haochen_database_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
