# Generated by Django 4.2.6 on 2024-01-26 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0010_passage_gpt_response_parsing_failed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, max_length=255)),
                ('chinese_meaning', models.CharField(db_index=True, max_length=255)),
                ('usage_context', models.TextField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_terms', to='passages.passage')),
            ],
        ),
    ]
