# Generated by Django 4.2.6 on 2024-04-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0012_passage_gpt_response_academic_terms_incorrect_removed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=500)),
                ('language', models.CharField(choices=[('EN', 'English'), ('CN', 'Chinese'), ('FR', 'French'), ('KR', 'Korean'), ('JP', 'Japanese'), ('DE', 'German'), ('ES', 'Spanish')], max_length=2)),
                ('lyrics_text', models.TextField()),
                ('chinese_translation', models.TextField(blank=True, null=True)),
                ('english_translation', models.TextField(blank=True, null=True)),
                ('list_of_tokens', models.TextField(blank=True, null=True)),
                ('sentences', models.ManyToManyField(blank=True, to='passages.sentence')),
            ],
        ),
    ]
