# Generated by Django 4.2.6 on 2024-04-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0013_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyrics',
            name='singer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
