# Generated by Django 4.2.6 on 2024-04-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0014_lyrics_singer'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='lyrics',
            field=models.ManyToManyField(blank=True, related_name='tokens', to='passages.lyrics'),
        ),
        migrations.AddField(
            model_name='token',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
