# Generated by Django 4.2.6 on 2024-04-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0015_token_lyrics_token_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='AI_Lyrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=500)),
                ('singer', models.CharField(blank=True, max_length=500, null=True)),
                ('language', models.CharField(choices=[('EN', 'English'), ('CN', 'Chinese'), ('FR', 'French'), ('KR', 'Korean'), ('JP', 'Japanese'), ('DE', 'German'), ('ES', 'Spanish')], max_length=2)),
                ('lyrics_text', models.TextField()),
                ('list_of_tokens', models.TextField(blank=True, null=True)),
                ('sentences', models.ManyToManyField(blank=True, to='passages.sentence')),
            ],
        ),
        migrations.AddField(
            model_name='token',
            name='ai_lyrics',
            field=models.ManyToManyField(blank=True, related_name='tokens', to='passages.ai_lyrics'),
        ),
    ]
