# Generated by Django 4.2.6 on 2024-04-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0017_album_lyrics_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='singer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
