# Generated by Django 4.2.6 on 2024-04-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0018_album_singer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='singer',
            field=models.CharField(default='Taylor Swift', max_length=255),
        ),
    ]
