# Generated by Django 4.2.6 on 2024-04-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0020_rename_chinese_translation_lyrics_lyrics_summary_chinese_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai_lyrics',
            name='inspired_by',
            field=models.ManyToManyField(blank=True, to='passages.lyrics'),
        ),
    ]
