# Generated by Django 4.2.6 on 2024-04-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0021_ai_lyrics_inspired_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai_lyrics',
            name='lyrics_with_translation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
