# Generated by Django 4.2.6 on 2024-04-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0022_ai_lyrics_lyrics_with_translation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ai_lyrics',
            old_name='lyrics_with_translation',
            new_name='lyrics_with_chinese_translation',
        ),
        migrations.AddField(
            model_name='ai_lyrics',
            name='lyrics_with_english_translation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
