# Generated by Django 4.2.6 on 2024-04-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0023_rename_lyrics_with_translation_ai_lyrics_lyrics_with_chinese_translation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='math_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, unique=True)),
                ('level', models.CharField(max_length=255, unique=True)),
                ('section', models.CharField(max_length=255, unique=True)),
                ('topic', models.CharField(max_length=255, unique=True)),
                ('english_text_problem', models.TextField()),
                ('haochen_data_problem', models.TextField()),
                ('english_text_solution', models.TextField()),
                ('haochen_data_solution', models.TextField()),
                ('haochen_database_id', models.CharField(blank=True, max_length=36, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='passage',
            name='order',
        ),
    ]
