# Generated by Django 4.2.6 on 2024-04-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0024_math_text_remove_passage_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='math_text',
            name='level',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='math_text',
            name='section',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='math_text',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='math_text',
            name='topic',
            field=models.CharField(max_length=255),
        ),
    ]
