# Generated by Django 4.2.6 on 2024-04-08 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0025_alter_math_text_level_alter_math_text_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathTextToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('lemma', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MathTokenOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('problem', 'Problem'), ('solution', 'Solution')], max_length=100)),
                ('pos_tag', models.CharField(max_length=50)),
                ('math_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passages.math_text')),
                ('math_text_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passages.mathtexttoken')),
            ],
            options={
                'unique_together': {('math_text', 'math_text_token', 'origin', 'pos_tag')},
            },
        ),
        migrations.AddField(
            model_name='mathtexttoken',
            name='math_text',
            field=models.ManyToManyField(related_name='tokens', through='passages.MathTokenOrigin', to='passages.math_text'),
        ),
    ]
