# Generated by Django 4.2.6 on 2024-04-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0026_mathtexttoken_mathtokenorigin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='math_text',
            name='section_merged',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
